# Generated by Django 4.2.13 on 2024-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=40)),
                ('passwordhash', models.CharField(max_length=32)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
