# Generated by Django 4.2.13 on 2024-07-07 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginportal', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sth_to_say', models.CharField(max_length=50, null=True)),
                ('level', models.IntegerField(null=True)),
                ('coin', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('BaseInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
