# Generated by Django 4.2.13 on 2024-07-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginportal', '0003_userextra_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='disabled',
        ),
    ]
